services:
    _defaults:
        autoconfigure: true

    contao.migration.referee_100.config_update:
        class: Teusal\ContaoRefereeHamburgBundle\Migration\ConfigMigration
        arguments:
            - '@contao.framework'

    contao.migration.referee_100.newsletter_update:
        class: Teusal\ContaoRefereeHamburgBundle\Migration\NewsletterMigration
        arguments:
            - '@database_connection'

    contao.migration.referee_100.season_update:
        class: Teusal\ContaoRefereeHamburgBundle\Migration\BsaSeasonMigration
        arguments:
            - '@database_connection'
