services:
    _defaults:
        autoconfigure: true

    contao.migration.bsa.newsletter_update:
        class: Teusal\ContaoRefereeHamburgBundle\Migration\NewsletterMigration
        arguments:
            - '@database_connection'
    contao.migration.bsa.season_update:
        class: Teusal\ContaoRefereeHamburgBundle\Migration\BsaSeasonMigration
        arguments:
            - '@database_connection'
