services:
    _defaults:
        autoconfigure: true

    contao.mailer.available_transports:
        class: Teusal\ContaoRefereeHamburgBundle\Library\Mailer\AvailableTransports
        public: true
        arguments:
            - '@?translator'

    teusal.referee.available_referees:
        class: Teusal\ContaoRefereeHamburgBundle\Library\Options\RefereeOptions
        public: true
        arguments:
            - false

    teusal.referee.available_referees.include_deleted:
        class: Teusal\ContaoRefereeHamburgBundle\Library\Options\RefereeOptions
        public: true
        arguments:
            - true
